export const languages = [
    { value: 'enUS', label: '🇺🇸 English (United States)' },
    { value: 'enGB', label: '🇬🇧 English (United Kingdom)' },
    { value: 'esES', label: '🇪🇸 Español (España)' },
    { value: 'esMX', label: '🇲🇽 Español (México)' },
    { value: 'frFR', label: '🇫🇷 Français (France)' },
    { value: 'deDE', label: '🇩🇪 Deutsch (Deutschland)' },
    { value: 'itIT', label: '🇮🇹 Italiano (Italia)' },
    { value: 'ptPT', label: '🇵🇹 Português (Portugal)' },
    { value: 'ptBR', label: '🇧🇷 Português (Brasil)' },
    { value: 'ruRU', label: '🇷🇺 Русский (Россия)' },
    { value: 'nlNL', label: '🇳🇱 Nederlands (Nederland)' },
    { value: 'svSE', label: '🇸🇪 Svenska (Sverige)' },
    { value: 'fiFI', label: '🇫🇮 Suomi (Suomi)' },
    { value: 'noNO', label: '🇳🇴 Norsk (Norge)' },
]